# Automatic build configuration for parcel model
language: python
sudo: false
notifications:
  email: false

# Borrowing schema from https://github.com/pydata/xarray/
matrix:
  include:
 - python: 2.7
   env: CONDA_ENV=py27
 - python: 3.4
   env: CONDA_ENV=py34
 - python: 3.5
   env: CONDA_ENV=py35

# Packages to install into test linux environment
addons:
  apt:
    packages:
    - cmake
    - liblapack-dev
    - libsundials-serial-dev
    - gfortran

# command to install dependencies (adapted from jakevdp/supersmoother)
# using miniconda
before_install:
    # - sudo apt-get update
    - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=$HOME/miniconda/bin:$PATH
    - hash -r
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    # For debugging conda
    - conda info -a

install:
    - conda env create --file ci/requirements-$CONDA_ENV.yml
    - source activate parcel_model
    # Build and install assimulo. If Python 3.5, we have to do this by hand
    # else we can rely on the existing conda package
    - if [[ "$CONDA_ENV" == "py35" ]]; then
        wget https://trac.jmodelica.org/assimulo/export/822/releases/Assimulo-2.8b1-fix.zip;
        unzip Assimulo-2.8b1-fix.zip;
        cd Assimulo-2.8b1;
        python setup.py install --sundials-home=/usr --lapack-home=/usr/lib;
      else
        conda install assimulo;
      fi
    # Done! Can now move on to the parcel model
    - pip install -e .

script:
    # Automated testng will go here
    - echo "Executing test simulation"
    - ./run_parcel examples/simple.yml
    - echo "Simple test executed sucessfully."
