name: pyrcel
channels:
    - conda-forge
dependencies:
    - python=2.7
    - assimulo
    - pandas
    - pyyaml
    - scipy
    - numba
    - numpy
    - xarray
    - numpydoc
    - ipython
    - sphinx
    - sphinx_rtd_theme